// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeasonalFood.Models;

#nullable disable

namespace SeasonalFood.Migrations
{
    [DbContext(typeof(SeasonalFoodContext))]
    [Migration("20230506205007_UpdateInCase")]
    partial class UpdateInCase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SeasonalFood.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HarvestSeason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PopularUses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SampleRecipe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Geography = "Northern hemisphere, East Asia, Australia.",
                            HarvestSeason = "Spring and early summer.",
                            Name = "Cherry",
                            PopularUses = "Eaten raw, baked into pies and cakes, jams, jellies, sauces, dried for later use",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 2,
                            Geography = "Today tomatoes are grown around the world.",
                            HarvestSeason = "Mid to late summer.",
                            Name = "Tomato",
                            PopularUses = "Eaten raw, in salads, processed into sauces, pastes and ketchup, made into salsas, soups, juice, cocktails, stewed, breaded, and fried.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 3,
                            Geography = "Today carrots are grown around the world.",
                            HarvestSeason = "If planted in early spring, harvest in early summer. If planted in late summer, harvest in fall or early winter.",
                            Name = "Carrot",
                            PopularUses = "Eaten raw, in salads, boiled, fried, steamed, made into soups and broths, baked into carrot cake, made into jams and preserves, dehydrated to turn into fried chips.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 4,
                            Geography = "Tropical and subtropical climates.",
                            HarvestSeason = "Oranges may be harvested at various times during the year; in the United States navel oranges may be harvested in cooler months.",
                            Name = "Orange",
                            PopularUses = "Eaten raw, made into juice, candied, the skin can be zested, made into jam, marmalade, and preserves, processed into oils",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 5,
                            Geography = "Tropical and subtropical climates.",
                            HarvestSeason = "Late summer through winter.",
                            Name = "Mango",
                            PopularUses = "Eaten raw, incorporated into desserts, added to many savory foods, used in salsas, made into lassi, processed into chutney.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 6,
                            Geography = "Tropical regions.",
                            HarvestSeason = "Late spring and early summer.",
                            Name = "Banana",
                            PopularUses = "Eaten raw, made into banana bread, pancakes, and muffins, made into shakes and smoothies, incorporated into many desserts.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 7,
                            Geography = "Native to the tropics, but varieties can be grown around the world.",
                            HarvestSeason = "Early autumn.",
                            Name = "Kiwi",
                            PopularUses = "Eaten raw, added into desserts and baked goods, added to salads",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 8,
                            Geography = "Tropical and sub-tropical regions.",
                            HarvestSeason = "Avocados are in season all year in Mexico.",
                            Name = "Avocado",
                            PopularUses = "Eaten in salads, made into guacamole, eaten on toast, made into smoothies, made into soups, used in sushi, juiced, incorporated into drinks and ice creams.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 9,
                            Geography = "Cooler regions.",
                            HarvestSeason = "Spring and early summer.",
                            Name = "Broccoli",
                            PopularUses = "Eaten raw, added to salads, steamed, stir-fried",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 10,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Cauliflower",
                            PopularUses = "",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 11,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Blueberries",
                            PopularUses = "",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 12,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Cabbage",
                            PopularUses = "",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 13,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Grapes",
                            PopularUses = "",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 14,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Dragonfruit",
                            PopularUses = "",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 15,
                            Geography = "",
                            HarvestSeason = "",
                            Name = "Watermelon",
                            PopularUses = "",
                            SampleRecipe = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
