// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeasonalFood.Models;

#nullable disable

namespace SeasonalFood.Migrations
{
    [DbContext(typeof(SeasonalFoodContext))]
    [Migration("20230506213800_FinishDatabaseInfo")]
    partial class FinishDatabaseInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SeasonalFood.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Geography")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HarvestSeason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PopularUses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SampleRecipe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Geography = "Northern hemisphere, East Asia, Australia.",
                            HarvestSeason = "Spring and early summer.",
                            Name = "Cherry",
                            PopularUses = "Eaten raw, baked into pies and cakes, jams, jellies, sauces, dried for later use",
                            SampleRecipe = "Quick and Easy Fresh Cherry Pie, by David Martin | cookeatshare.com | https://cookeatshare.com/recipes/quick-and-easy-fresh-cherry-pie-692039"
                        },
                        new
                        {
                            FoodId = 2,
                            Geography = "Today tomatoes are grown around the world.",
                            HarvestSeason = "Mid to late summer.",
                            Name = "Tomato",
                            PopularUses = "Eaten raw, in salads, processed into sauces, pastes and ketchup, made into salsas, soups, juice, cocktails, stewed, breaded, and fried.",
                            SampleRecipe = "Mediterranean Lamb Stew with tomato, mushroom and eggplant (Kokkinisto), by John Spottiswood | cookeatshare.com |https://cookeatshare.com/recipes/mediterranean-lamb-stew-with-tomato-mushroom-and-eggplant-kokkinisto-797643"
                        },
                        new
                        {
                            FoodId = 3,
                            Geography = "Today carrots are grown around the world.",
                            HarvestSeason = "If planted in early spring, harvest in early summer. If planted in late summer, harvest in fall or early winter.",
                            Name = "Carrot",
                            PopularUses = "Eaten raw, in salads, boiled, fried, steamed, made into soups and broths, baked into carrot cake, made into jams and preserves, dehydrated to turn into fried chips.",
                            SampleRecipe = "Carrot and Red Lentil Soup, by Easy Cook - Laka kuharica | cookeatshare.com | https://cookeatshare.com/recipes/carrot-and-red-lentils-soup-761174"
                        },
                        new
                        {
                            FoodId = 4,
                            Geography = "Tropical and subtropical climates.",
                            HarvestSeason = "Oranges may be harvested at various times during the year; in the United States navel oranges may be harvested in cooler months.",
                            Name = "Orange",
                            PopularUses = "Eaten raw, made into juice, candied, the skin can be zested, made into jam, marmalade, and preserves, processed into oils",
                            SampleRecipe = "Smoked Orange Peel Chicken, by Patti Fisher | cookeatshare.com | https://cookeatshare.com/recipes/smoked-orange-peel-chicken-793501"
                        },
                        new
                        {
                            FoodId = 5,
                            Geography = "Tropical and subtropical climates.",
                            HarvestSeason = "Late summer through winter.",
                            Name = "Mango",
                            PopularUses = "Eaten raw, incorporated into desserts, added to many savory foods, used in salsas, made into lassi, processed into chutney.",
                            SampleRecipe = "Mango Lassi, by pshinde2109 | cookeatshare.com | https://cookeatshare.com/recipes/mango-lassi-743042"
                        },
                        new
                        {
                            FoodId = 6,
                            Geography = "Tropical regions.",
                            HarvestSeason = "Late spring and early summer.",
                            Name = "Banana",
                            PopularUses = "Eaten raw, made into banana bread, pancakes, and muffins, made into shakes and smoothies, incorporated into many desserts.",
                            SampleRecipe = "Easy Banana Bread, by ShaleeDP | cookeatshare.com | https://cookeatshare.com/recipes/easy-banana-bread-719687"
                        },
                        new
                        {
                            FoodId = 7,
                            Geography = "Native to the tropics, but varieties can be grown around the world.",
                            HarvestSeason = "Early autumn.",
                            Name = "Kiwi",
                            PopularUses = "Eaten raw, added into desserts and baked goods, added to salads",
                            SampleRecipe = "Chocolate Kiwi Smoothie, by Nupur UKrasoi | cookeatshare.com | https://cookeatshare.com/recipes/chocolate-kiwi-smoothie-700004"
                        },
                        new
                        {
                            FoodId = 8,
                            Geography = "Tropical and sub-tropical regions.",
                            HarvestSeason = "Avocados are in season all year in Mexico.",
                            Name = "Avocado",
                            PopularUses = "Eaten in salads, made into guacamole, eaten on toast, made into smoothies, made into soups, used in sushi, juiced, incorporated into drinks and ice creams.",
                            SampleRecipe = "Quinoa Salad with Broccoli and Chickpeas, by Ronda | cookeatshare.com | https://cookeatshare.com/recipes/quinoa-salad-with-broccoli-and-chickpeas-707082"
                        },
                        new
                        {
                            FoodId = 9,
                            Geography = "Cooler regions.",
                            HarvestSeason = "Spring and early summer.",
                            Name = "Broccoli",
                            PopularUses = "Eaten raw, added to salads, steamed, stir-fried.",
                            SampleRecipe = ""
                        },
                        new
                        {
                            FoodId = 10,
                            Geography = "Cool-weather climates.",
                            HarvestSeason = "Early fall, spring.",
                            Name = "Cauliflower",
                            PopularUses = "Eaten raw, roasted, grilled, steamed, pickled, made into pizza crust, mashed like potatoes.",
                            SampleRecipe = "Gobi (Cauliflower) Manchurian, by Hina Gujral | cookeatshare.com | https://cookeatshare.com/recipes/gobi-cauliflower-manchurian-772137"
                        },
                        new
                        {
                            FoodId = 11,
                            Geography = "Humid northern climates, coastal regions.",
                            HarvestSeason = "Spring and summer.",
                            Name = "Blueberries",
                            PopularUses = "Eaten raw, added to fruit salads, made into jellies and jams, pureed, baked into muffins, pancakes, pies, fermented for wine.",
                            SampleRecipe = "Banana Blueberry Muffin, by Simmy Routroy | cookeatshare.com | https://cookeatshare.com/recipes/banana-blueberry-muffin-810851"
                        },
                        new
                        {
                            FoodId = 12,
                            Geography = "World-wide, areas with cool temperatures and moisture.",
                            HarvestSeason = "Late summer to late fall.",
                            Name = "Cabbage",
                            PopularUses = "Eaten raw, steamed, pickled, stewed, sauteed, made into soups, sourkraut, kimchi, in stuffed cabbage dishes, and dumplings.",
                            SampleRecipe = "Stuffed Cabbage (Golabki), by Therese | cookeatshare.com | https://cookeatshare.com/recipes/stuffed-cabbage-golabki-664567"
                        },
                        new
                        {
                            FoodId = 13,
                            Geography = "Areas with milder climates.",
                            HarvestSeason = "Early autumn.",
                            Name = "Grapes",
                            PopularUses = "Eaten raw, added to fruit salads, made into jellies and jams, dried into raisins, made into juice, fermented for wine.",
                            SampleRecipe = "Fresh and Easy Grape Sherbet, by Catherine Pappas | cookeatshare.com | https://cookeatshare.com/recipes/fresh-and-easy-grape-sherbet-686486"
                        },
                        new
                        {
                            FoodId = 14,
                            Geography = "Tropical regions.",
                            HarvestSeason = "Summer.",
                            Name = "Dragon fruit",
                            PopularUses = "Eaten raw, used for juices and teas.",
                            SampleRecipe = "No Bake Dessert | Tropical Coconut Milk Rice Pudding … with dragon fruit & rambutans, by Deeba Rajpal | cookeatshare.com | https://cookeatshare.com/recipes/no-bake-dessert-tropical-coconut-milk-rice-pudding-with-dragon-fruit-rambutans-719670/external"
                        },
                        new
                        {
                            FoodId = 15,
                            Geography = "Tropical to temperate climates.",
                            HarvestSeason = "Summer.",
                            Name = "Watermelon",
                            PopularUses = "Eaten raw, added to fruit salads, made into juice and wine.",
                            SampleRecipe = "Watermelon Salsa, by Kelsey Martin | cookeatshare.com | https://cookeatshare.com/recipes/watermelon-salsa-587"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
